/* Print-ready one-course group roadmap renderer. */
(function (root) {
  "use strict";
  function e(v) { return v == null ? "" : String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
  function pct(v) { return v == null ? "—" : Math.round(v * 1000) / 10 + "%"; }
  function pp(v) { return v == null ? "—" : Math.round(v * 1000) / 10 + " pp"; }
  function slug(v) { return String(v || "group").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"") || "group"; }
  function section(v) { return v === "english" ? "Reading & Writing" : "Math"; }
  function label(v) { return String(v || "").replace(/_/g," "); }
  function bar(name, value, max, color) { var width = max ? Math.max(2, Math.min(100, value * 100 / max)) : 0; return '<div class="bar"><div><b>' + e(name) + '</b><span>' + e(value) + ' h</span></div><i><u style="width:' + width + '%;background:' + color + '"></u></i></div>'; }
  var CSS = [
    '*{box-sizing:border-box}','html{-webkit-print-color-adjust:exact;print-color-adjust:exact;background:#dfe4ec}','body{margin:0;background:#dfe4ec;color:#101725;font-family:Arial,Helvetica,sans-serif;font-size:10px;line-height:1.4}',
    '.page{width:210mm;height:297mm;margin:8mm auto;background:#fff;padding:14mm 15mm 12mm;position:relative;overflow:hidden;page-break-after:always;break-after:page}.page:last-child{page-break-after:auto;break-after:auto}',
    '.cover{background:linear-gradient(145deg,#07142f 0,#0e2e68 64%,#1740a9 100%);color:#fff}.brand{font-size:9px;letter-spacing:.22em;color:#ff963e;font-weight:700}.hero{margin-top:30mm}.hero h1{font-size:39px;line-height:.98;margin:4mm 0;letter-spacing:-.04em}.hero p{font-size:14px;max-width:120mm;color:#d9e3f5}.cover-grid{position:absolute;left:15mm;right:15mm;bottom:28mm;display:grid;grid-template-columns:repeat(4,1fr);gap:3mm}.cover-stat{border-top:2px solid #ff963e;padding-top:3mm}.cover-stat b{font-size:23px;display:block}.cover-stat span{font-size:7px;letter-spacing:.12em;color:#c8d4e8}',
    '.mast{display:flex;justify-content:space-between;border-bottom:2px solid #0c1730;padding-bottom:4mm;margin-bottom:5mm}.kicker{color:#c7560a;font-size:7px;letter-spacing:.18em;font-weight:700}.mast h1{font-size:24px;margin:1mm 0;color:#0c1730}.meta{text-align:right;color:#637083;font-size:8px}',
    'h2{font-size:14px;color:#0c1730;margin:5mm 0 2mm;border-left:4px solid #ff963e;padding-left:3mm}h3{font-size:10px;margin:1mm 0}p{color:#566174;margin:1mm 0}',
    '.grid2{display:grid;grid-template-columns:1fr 1fr;gap:5mm}.card{border:1px solid #dfe4ec;border-radius:3mm;padding:4mm;background:#fff}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:2mm}.stat{background:#f1f5fb;border-radius:2mm;padding:3mm}.stat b{font-size:17px;color:#1740a9;display:block}.stat span{font-size:6.5px;color:#6a7484;letter-spacing:.1em}',
    '.bar{margin:3mm 0}.bar>div{display:flex;justify-content:space-between}.bar span{color:#697486}.bar i{height:4mm;background:#e6eaf0;border-radius:99px;display:block;overflow:hidden;margin-top:1mm}.bar u{display:block;height:100%;border-radius:99px}',
    '.item{padding:3mm 0;border-bottom:1px solid #e5e9ef}.item:last-child{border:0}.item b{font-size:10px}.pill{float:right;border-radius:99px;padding:1mm 2mm;background:#e9effa;color:#1740a9;font-size:6.5px;font-weight:700}.warning{background:#fff5ed;border-left:3px solid #e16d22;padding:3mm;margin:2mm 0;color:#693314}',
    'table{width:100%;border-collapse:collapse;table-layout:fixed}th{background:#0c1730;color:#fff;font-size:7px;text-align:left;padding:2mm}td{font-size:7.2px;padding:1.8mm 2mm;border-bottom:1px solid #e5e9ef;vertical-align:top}tr:nth-child(even) td{background:#f8fafc}th:nth-child(1){width:31%}th:nth-child(2){width:16%}th:nth-child(3){width:14%}th:nth-child(4){width:10%}th:nth-child(5){width:29%}.diff{color:#a64811;font-weight:700}',
    '.strategy{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm}.strategy .card b{font-size:18px;color:#1740a9;display:block}.note{background:#eef3fc;border-radius:2mm;padding:3mm;color:#3e4a5d}.footer{position:absolute;bottom:5mm;left:15mm;right:15mm;display:flex;justify-content:space-between;border-top:1px solid #dfe4ec;padding-top:2mm;font-size:6px;color:#7a8494}',
    '@page{size:A4;margin:0}','@media print{html,body{background:#fff}.page{margin:0}}'
  ].join("");
  function lessonRows(list, pooled) { return list.map(function (l) { var p = pooled.lessons[l.lesson_id]; return '<tr><td><b>' + e(l.lesson_name) + '</b></td><td>' + e(section(l.section)) + '</td><td>' + e(label(l.priority)) + '</td><td><b>' + e(l.group_hours) + ' h</b></td><td class="' + (l.needs_differentiation ? "diff" : "") + '">' + e((p.administered ? p.correct + "/" + p.administered + " · " + pct(p.accuracy) : "Not assessed") + (l.needs_differentiation ? " · Mixed readiness—use tiered practice." : " · Shared core instruction.")) + '</td></tr>'; }).join(""); }
  function renderSharedGroupRoadmap(result) {
    if (!result || !result.ok || !result.roadmap) throw new Error("Load a valid group case with at least two eligible students before creating a group roadmap.");
    var g=result.group, r=result.roadmap, t=result.totals, p=result.pooled, seq=r.lesson_sequence, split=Math.ceil(seq.length/2), max=Math.max(t.english_group_hours,t.math_group_hours,t.strategy_hours);
    var warningText = result.similarity.level === "high" ? "Performance variation is high in " + result.similarity.flags.map(function (x) { return x.label; }).join(", ") + ". Students may need differentiated practice even though the core lesson can still be taught together." : "Performance similarity is " + result.similarity.label.toLowerCase() + ". Continue to monitor lesson-level readiness.";
    return '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + e(slug(g.group_name) + "_group-roadmap") + '</title><style>' + CSS + '</style></head><body>' +
      '<section class="page cover"><div class="brand">TESTPREP · HOUSE OF PREP</div><div class="hero"><div class="kicker">ONE GROUP · ONE COURSE · ONE SHARED SEQUENCE</div><h1>' + e(g.group_name) + '<br>Shared SAT Roadmap</h1><p>A pooled diagnostic plan for common instruction, targeted differentiation, and measurable progress.</p></div><div class="cover-grid"><div class="cover-stat"><b>' + g.valid_student_count + '</b><span>VALID STUDENTS</span></div><div class="cover-stat"><b>' + seq.length + '</b><span>SHARED LESSONS</span></div><div class="cover-stat"><b>' + t.final_planned_total + ' h</b><span>ONE GROUP COURSE</span></div><div class="cover-stat"><b>' + e(result.similarity.label) + '</b><span>SIMILARITY</span></div></div><div class="footer" style="color:#b7c6df;border-color:rgba(255,255,255,.2)"><span>' + e(g.assessment_title) + '</span><span>GROUP ROADMAP · 1</span></div></section>' +
      '<section class="page"><div class="mast"><div><div class="kicker">GROUP PROFILE</div><h1>The instructional starting point</h1></div><div class="meta">' + e(g.group_name) + '<br>' + e(g.valid_student_count) + ' valid · ' + e(g.excluded_student_count) + ' excluded<br>' + e(g.diagnostic_date_range || "Date not provided") + '</div></div><div class="summary"><div class="stat"><b>' + pct(p.overall.accuracy) + '</b><span>POOLED ACCURACY</span></div><div class="stat"><b>' + Math.round(result.score_statistics.total.mean || 0) + '</b><span>AVERAGE SCORE</span></div><div class="stat"><b>' + r.group_multiplier + '×</b><span>GROUP TIME</span></div><div class="stat"><b>' + e(result.schedule.recommended_weeks) + '</b><span>WEEKS</span></div></div><div class="grid2"><div class="card"><h2>Course allocation</h2>' + bar("Reading & Writing",t.english_group_hours,max,"#1740a9") + bar("Math",t.math_group_hours,max,"#ff963e") + bar("Strategy",t.strategy_hours,max,"#2b8a64") + '<div class="note">Hours form one shared plan. They are never added once per student and the 2.0 multiplier does not grow with roster size.</div></div><div class="card"><h2>Similarity and differentiation</h2><div class="warning">' + e(warningText) + '</div>' + result.variation_flags.slice(0,4).map(function (l) { return '<div class="item"><span class="pill">SD ' + e(pp(l.accuracy_sd)) + '</span><b>' + e(l.lesson_name) + '</b><p>Teach the core together, then use support, standard, and extension practice.</p></div>'; }).join("") + '</div></div><div class="grid2"><div class="card"><h2>Strongest shared evidence</h2>' + result.strengths.map(function (x) { return '<div class="item"><b>' + e(x.lesson_name) + '</b><p>' + e(x.correct + "/" + x.administered + " pooled · " + pct(x.accuracy)) + '</p></div>'; }).join("") + '</div><div class="card"><h2>First instructional priorities</h2>' + result.priority_areas.map(function (x) { return '<div class="item"><span class="pill">' + e(label(x.priority)) + '</span><b>' + e(x.lesson_name) + '</b><p>' + e(x.correct + "/" + x.administered + " pooled · " + x.group_hours + " group hours") + '</p></div>'; }).join("") + '</div></div><div class="footer"><span>TESTPREP · GROUP PROFILE</span><span>2</span></div></section>' +
      '<section class="page"><div class="mast"><div><div class="kicker">SHARED SEQUENCE · PART 1</div><h1>Teach the highest-need units first</h1></div><div class="meta">Lessons 1–' + split + '<br>Each lesson appears once.</div></div><table><thead><tr><th>Lesson</th><th>Section</th><th>Priority</th><th>Group time</th><th>Evidence / delivery</th></tr></thead><tbody>' + lessonRows(seq.slice(0,split),p) + '</tbody></table><div class="note" style="margin-top:5mm"><b>Sequence rule.</b> Units are ranked by the same urgency-and-hours logic used by the individual roadmap, and lessons stay in their configured instructional order within each unit.</div><div class="footer"><span>TESTPREP · SHARED LESSON SEQUENCE</span><span>3</span></div></section>' +
      '<section class="page"><div class="mast"><div><div class="kicker">SHARED SEQUENCE · PART 2</div><h1>Complete, rehearse, and reassess</h1></div><div class="meta">Lessons ' + (split+1) + '–' + seq.length + '<br>Total: ' + t.final_planned_total + ' h</div></div><table><thead><tr><th>Lesson</th><th>Section</th><th>Priority</th><th>Group time</th><th>Evidence / delivery</th></tr></thead><tbody>' + lessonRows(seq.slice(split),p) + '</tbody></table><h2>Shared strategy time</h2><div class="strategy"><div class="card"><b>' + r.strategy.orientation_hours + ' h</b>Orientation, methods, and baseline routines</div><div class="card"><b>' + r.strategy.final_review_hours + ' h</b>Final review, pacing, and rehearsal</div><div class="card"><b>' + r.strategy.scheduled_hours + ' h</b>Scheduled strategy total after group rules</div></div><h2>Teaching approach</h2><div class="grid2"><div class="note"><b>Common instruction.</b> Explain and model one core lesson for everyone. Use quick checks before releasing students to practice.</div><div class="note"><b>Differentiated practice.</b> In flagged lessons, assign foundational support, standard guided work, or advanced extension without splitting the shared roadmap.</div></div><div class="warning" style="margin-top:4mm">The roadmap uses pooled diagnostic performance and a fixed 2.0 group-time multiplier. It is not the sum or average of individual course plans.</div>' + (result.excluded_students.length ? '<div class="warning"><b>Excluded students:</b> ' + result.excluded_students.map(function (x) { return e(x.student_name + " — " + x.reason); }).join(" · ") + '</div>' : '') + '<div class="footer"><span>TESTPREP · DELIVERY AND REASSESSMENT</span><span>4</span></div></section></body></html>';
  }
  var API={renderSharedGroupRoadmap:renderSharedGroupRoadmap,slug:slug};
  if(typeof module!=="undefined"&&module.exports)module.exports=API;
  root.TP_GROUP_ROADMAP=API;
})(typeof globalThis!=="undefined"?globalThis:this);
